### ISSUE TITLE
opam package

### ISSUE THREAD

**Issue by Armael** [tokenrove/tsdl-image#1]
Hi,

Contrary to what the README pretends, there doesn't seem to be an opam package? :p 

– Armaël

EDIT: oh, but I guess @dbuenzli would need to do a new release of tsdl before.

**Comment by tokenrove** [comment]
This is unfortunately true (there is opam packaging, and you should be able to install it with `opam pin`), but I am waiting on a release of the next version of Tsdl to be able to make a release on opam.

**Comment by tokenrove** [comment]
I will try to get the time to remedy this issue this week.  Thanks for reporting it.

**Comment by Armael** [comment]
Thanks!

**Comment by dbuenzli** [comment]
Will do soon.

**Comment by tokenrove** [comment]
@dbuenzli I was hoping to get one last kick at that audio issue before asking you to make a release but I don't think I'm going to have time.  Sorry.

**Comment by dbuenzli** [comment]
Release done: https://github.com/ocaml/opam-repository/pull/5163.

**Comment by tokenrove** [comment]
Awesome, thanks.  As soon as that PR is merged, I'll opam-publish this package.  (BTW, now is a good time to report any obvious bugs...)

**Comment by tokenrove** [comment]
Sorry for the delay on this, but I should have the time to get this into opam on Saturday.  Thanks for your patience.

**Comment by tokenrove** [comment]
https://github.com/ocaml/opam-repository/pull/5197

**Comment by Armael** [comment]
Awesome! Thanks.
