### ISSUE TITLE
Opam package version (again)

### ISSUE THREAD

**Issue by Firobe** [tokenrove/tsdl-image#14]
Hello, and thank you for your work on tsdl-image and its siblings !

I was wondering if you could release the latest release to opam, since it's still the ~0.1.2~ 0.2.0 there. 
It would be nice to have the latest API and support. Also, with the current state of opam, the command you state on the README (using package name `tsdl_image`) does not work (wrong package name).

Cheers

**Comment by Firobe** [comment]
Note that I might be able to take over maintenance of the three libraries if needed (I saw you were looking for that in other issues).

**Comment by tokenrove** [comment]
You're totally welcome to take over maintenance of these libraries.  I'd recommend reverting the changes I made to adapt this one to dune.

**Comment by Firobe** [comment]
Okay. For now I'm experimenting a bit with everything.

> I'd recommend reverting the changes I made to adapt this one to dune.

Any reason for that ? I thought it was a good idea, and probably would've done the same for the other libraries.

**Comment by Firobe** [comment]
If the reason is the forced name change, then it's not a problem (see https://github.com/tokenrove/tsdl-image/pull/16)

**Comment by Firobe** [comment]
If you wish to transfer the repos (or any other way you want), feel free to :)

**Comment by sanette** [comment]
it would be great if you could release the latest version to opam
currently the 0.2.0 version on opam requires result < 1.5 for some reason and this turns out to be quite a problem
(impossible to install ocaml-lsp-server)

**Comment by sanette** [comment]
(and this prevents me from upgrading my `bogue` library)

**Comment by sanette** [comment]
line 13 you should replace `compare` by `Stdlib.compare`

**Comment by sanette** [comment]
I would also add `name: "tsdl-image"` in the opam file to make it compatible with older opam versions

**Comment by sanette** [comment]
this is fixed in https://github.com/tokenrove/tsdl-image/pull/17
