### ISSUE TITLE
setup.ml Fails to compile

### ISSUE THREAD

**Issue by finnschiermer** [tokenrove/tsdl-image#3]
Hi, I'm trying to install tsdl-image through opam, but it fails with a compiler error:

Output from opam:
(I've put a '.' in the beginning of each line to avoid interpretation as markdown)

.#=== ERROR while compiling tsdl-image.0.1 =====================================#
.# opam-version 1.3.0~dev3 (a8e79a514a790d4bf23810f1322f3af99971016e)
.# os           linux
.# command      ocaml setup.ml -build
.# path         /home/finn/.opam/4.02.1/build/tsdl-image.0.1
.# exit-code    1
.# env-file     /home/finn/.opam/4.02.1/build/tsdl-image.0.1/tsdl-image-22501-6d07ae.env
.# stdout-file  /home/finn/.opam/4.02.1/build/tsdl-image.0.1/tsdl-image-22501-6d07ae.out
.# stderr-file  /home/finn/.opam/4.02.1/build/tsdl-image.0.1/tsdl-image-22501-6d07ae.err
.### stdout ###
.# [...]
.# + /home/finn/.opam/4.02.1/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package ctypes -package tsdl -I test -I src -o test/test.cmo test/test.ml
.# File "test/test.ml", line 13, characters 6-16:
.# Warning 8: this pattern-matching is not exhaustive.
.# Here is an example of a value that is not matched:
.# None
.# File "test/test.ml", line 16, characters 2-34:
.# Error: This expression has type
.#          Tsdl.Sdl.rw_ops Tsdl.Sdl.result =
.#            (Tsdl.Sdl.rw_ops, [ `Msg of string ]) Result.result
.#        but an expression was expected of type
.#          [<`Error of string | `Ok of 'a ]
.# Command exited with code 2.
.### stderr ###
.# E: Failure("Command ''/home/finn/.opam/4.02.1/bin/ocamlbuild' src/tsdl_image.cma src/tsdl_image.cmxa src/tsdl_image.a src/tsdl_image.cmxs test/test.byte -tag debug' terminated with error code 10")

**Comment by tokenrove** [comment]
This appears to be because of the new Result API in Tsdl.  I'll fix this on the weekend.

BTW, you can use ``` (three graves) at the start of a line to include verbatim examples.

**Comment by finnschiermer** [comment]
Nice. Thx.

**Comment by tokenrove** [comment]
https://github.com/ocaml/opam-repository/pull/5339
