### ISSUE TITLE
Opam version of tsdl-image 

### ISSUE THREAD

**Issue by mattiasdrp** [tokenrove/tsdl-image#8]
I want to use tsdl-image but with tsdl 0.9.0 and it looks like you updated it to go well with this version but I can't install the 0.1.1 version because my tsdl version is too recent and I can't install the 0.1 version because there is a problem with the tests (everything according to OPAM).

What I did is cloning the project and compile it on my own and then make install and I have a nice tsdl-image.0.1.1 working with tsdl.0.9.

The only problem is I had some warnings : 

```
+ /home/***/.opam/4.03.0/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -package ctypes -package tsdl -I src -o src/tsdl_image.cmx src/tsdl_image.ml
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Foreign, and its interface was not compiled with -opaque
+ /home/***/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I src -package ctypes -package result -package tsdl -I test -I src -o test/test.cmo test/test.ml
File "test/test.ml", line 14, characters 6-16:
Warning 8: this pattern-matching is not exhaustive.
```

And when I do `./test.byte` I have this error : 

`````` ./test.byte
Fatal error: exception File "test/test.ml", line 14, characters 6-11: Pattern matching failed```
``````

**Comment by tokenrove** [comment]
https://github.com/ocaml/opam-repository/pull/7015

If this pull request succeeds, 0.1.2 will be packaged.  As for why I hadn't done that yet, I can only assume it's because I thought I would get some time to make some improvements to this project before now.  Anyway, hopefully when that's in OPAM, your problem will be resolved.

Thanks.

**Comment by tokenrove** [comment]
tsdl-image 0.1.2 should now be in OPAM, so I'm marking this as resolved.  Let me know if there are any more problems.  Thanks.

**Comment by mattiasdrp** [comment]
For now everything is working. Thanks a lot !
